language: scala

jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)


jobs:
  include:
    # stage="test" if no stage is specified
    - env: TEST="compile"
      script: sbt compile
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release